library(maptools)
library(RColorBrewer)
library(classInt)
library(OpenStreetMap)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)
EW <- geojson_read("http://geoportal.statistics.gov.uk/datasets/8edafbe3276d4b56aec60991cbddda50_2.geojson", what = "sp")
#pull out london using grep and the regex wildcard for'start of the string' (^) to to look for the bit of the district code that relates to London (E09) from the 'lad15cd' column in the data slot of our spatial polygons dataframe
LondonMap <- EW[grep("^E09",EW@data$lad15cd),]
#plot it using the base plot function
qtm(LondonMap)
#read the shapefile into a simple features object
BoroughMapSF <- read_shape("england_lad_2011.shp", as.sf = TRUE)
BoroughMapSP <- LondonMap
#plot it very quickly asking qtm (quick thematic map) to check it has been read in correctly
qtm(BoroughMapSF)
qtm(BoroughMapSP)
library(methods)
class(BoroughMapSF)
class(BoroughMapSP)
newSF <- st_as_sf(BoroughMapSP)
newSP <- as(newSF, "Spatial")
BoroughMapSP <- as(BoroughMapSF, "Spatial")
#join the data to the @data slot in the SP data frame
BoroughMapSP@data <- data.frame(BoroughMapSP@data,LondonData[match(BoroughMapSP@data[,"code"],LondonData[,"New.code"]),])
#check it's joined.
head(BoroughMapSP@data)
BoroughDataMap <- append_data(BoroughMapSF,LondonData, key.shp = "code", key.data = "New.code", ignore.duplicates = TRUE)

library(tmap)
library(tmaptools)
tmap_mode("plot")
qtm(BoroughDataMap, fill = "Rate.of.JobSeekers.Allowance..JSA..Claimants...2015")
london_osm <- read_osm(BoroughDataMap, type = "esri", zoom = NULL)
qtm(london_osm) + 
  tm_shape(BoroughDataMap) + 
  tm_polygons("Rate.of.JobSeekers.Allowance..JSA..Claimants...2015", 
              style="jenks",
              palette="YlOrBr",
              midpoint=NA,
              title="Rate per 1,000 people",
              alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Job seekers' Allowance Claimants", legend.position = c("right", "bottom"))

tm_shape(BoroughDataMap) +
  tm_polygons(c("Average.Public.Transport.Accessibility.score...2014", "Violence.against.the.person.rate...2014.15"), 
              style=c("jenks", "pretty"),
              palette=list("YlOrBr", "Purples"),
              auto.palette.mapping=FALSE,
              title=c("Average Public Transport Accessibility", "Violence Against the Person Rate"))
install.packages("shinyjs")
library(shinyjs)
tmaptools::palette_explorer()
tmap_mode("view")
tm_shape(BoroughDataMap) +
  tm_polygons("X..children.in.year.6.who.are.obese..2011.12.to.2013.14",
              style="jenks",
              palette="PuRd",
              midpoint=NA,
              title="Truffle Shuffle Intensity")
save_tmap(filename = "truffle.html")
ggplot()+geom_sf(mapping = aes(geometry=geometry),data = BoroughDataMap)+theme_minimal()
ggplot()+geom_sf(mapping = aes(geometry=geometry, fill=Median.House.Price...U.00A3.....2014),data = BoroughDataMap)+theme_minimal()
palette1<-scale_fill_continuous(low="white", high="orange", "Price(£)")
labels<-labs(list(title="Average House Price 2014",x="Longitude", y="Latitude"))
ggplot()+geom_sf(mapping = aes(geometry=geometry, fill=Median.House.Price...U.00A3.....2014),data = BoroughDataMap)+theme_minimal()+palette1+labels
print(BoroughMapSP)
print(BoroughMapSF)
BoroughMapSP <- read_shape("BoundaryData/england_lad_2011Polygon.shp", current.projection = 27700)
BoroughMapSF <- st_read("BoundaryData/england_lad_2011Polygon.shp") %>% st_set_crs(27700)
UKBNG <- "+init=epsg:27700"
proj4string(BoroughMapSP) <- CRS(UKBNG)
print(BoroughMapSP) # check for new CRS
BoroughMapSF <- BoroughMapSF %>% st_set_crs(27700)
print(BoroughMapSF)
BoroughMapSPWGS84 <-spTransform(BoroughMapSP, CRS("+proj=longlat +datum=WGS84"))
print(BoroughMapSPWGS84)
BoroughMapSPBNG <-spTransform(BoroughMapSP, CRS(UKBNG))
print(BoroughMapSPBNG)
latlong <- "+init=epsg:4326"
BoroughMapSFWGS84 <- st_transform(BoroughMapSF, 4326)
print(BoroughMapSFWGS84)
install.packages("ggmap")
library(ggmap)
BoroughDataMap <- append_data(BoroughMapSFWGS84,LondonData, key.shp = "code", key.data = "New.code", ignore.duplicates = TRUE)

londonbbox1 <- c(left = -0.5103766, bottom = 51.28676, right = 0.3340146, top = 51.69187)

londonbbox2 <- as.vector(st_bbox(BoroughMapSFWGS84))
#this bit of code gets 
map <- get_stamenmap(londonbbox2, zoom = 10, maptype = "toner-lite")

ggmap(map) + geom_sf(mapping = aes(geometry=geometry, fill=Median.House.Price...U.00A3.....2014),data = BoroughDataMap, inherit.aes = FALSE,alpha=0.7)+theme_minimal()+palette1+labels
library(reshape2)
library(dplyr)
borough_melt<-melt(BoroughDataMap,id.vars=1:6, measure.vars=7:32)
borough_melt<-left_join(borough_melt,BoroughDataMap,by=c("code" = "code"))
borough_melt<-borough_melt[,c(1:8,78)]
library(tmap)
library(sf)
borough_melt<-st_as_sf(borough_melt)
tmap_mode("plot")
qtm(borough_melt,fill="value",by="variable")
ggplot()+geom_sf(mapping=aes(geometry=geometry, fill=value),data=borough_melt)+facet_wrap(~variable)
library(leaflet)
library(sf)
library(sp)
library(magrittr)
library(classInt)
library(RColorBrewer)
colours<- brewer.pal(5, "Blues")
breaks<-classIntervals(BoroughDataMap$Claimant.Rate.of.Housing.Benefit..2015.,n=5,style="jenks")
graphics::plot(breaks,pal=colours)
summary(breaks)
breaks <- breaks$brks

#create a new sp object from the earlier sf object with all of our data in THEN Transform it to WGS84 THEN convert it to SP.  

BoroughDataMapSP <- BoroughDataMap %>%
  st_transform(crs = 4326) %>%
  as("Spatial")

#create a colour palette using colorBin colour mapping
pal <- colorBin(palette = "YlOrRd", 
                domain = BoroughDataMapSP$Claimant.Rate.of.Housing.Benefit..2015.,
                #create bins using the breaks object from earlier
                bins = breaks)
# now, add some polygons colour them using your colour palette, #overlay the, on top of a nice backdrop and add a legend. Note the #use of the magrittr pipe operator (%>%) – check the documentation #to understand how this is working…
leaflet(BoroughDataMapSP) %>%
  addPolygons(stroke = FALSE, 
              fillOpacity = 0.5, 
              smoothFactor = 0.5,
              color = ~pal(Claimant.Rate.of.Housing.Benefit..2015.),
              popup = ~name
  ) %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  addLegend("bottomright", 
            pal= pal, 
            values = ~Claimant.Rate.of.Housing.Benefit..2015., 
            title = "Housing Benefit Claimant Rate", 
            labFormat = labelFormat(prefix = "Per 1,000 people "),
            opacity = 1
  )
